module fdata2pyplot

    use iso_fortran_env, only: real32, real64, real128
    implicit none
    private

    character(*), parameter :: py_file_name = 'plt.py'

    public :: fdata2pyplot_pass_data, fdata2pyplot_add_others
    interface fdata2pyplot_pass_data
        #:for nd in ['1d', '2d']
        #:for dtype in ['real32', 'real64', 'real128']
        module procedure fdata2pyplot_pass_${nd}$_${dtype}$_data
        #:endfor
        #:endfor
    end interface fdata2pyplot_pass_data

    contains

        function unopened_unit() result(unit)
            integer :: unit
            logical :: opened
            unit = 10
            do while (.true.)
                inquire(unit=unit, opened=opened)
                if (.not. opened) then
                    exit
                else
                    unit = unit + 1
                end if
            end do
        end function unopened_unit

        subroutine init()
            integer :: unit
            logical, save :: initialized = .false.
            if (.not. initialized) then
                unit = unopened_unit()
                open(unit=unit, file=py_file_name, status='REPLACE', &
                     action='WRITE', position='APPEND')
                write(unit=unit, fmt='(A)') "import numpy as np"
                write(unit=unit, fmt='(A)') "import matplotlib.pyplot as plt"
                close(unit=unit)
                initialized = .true.
            end if
        end subroutine init

        #:for nd in ['1d', '2d']
        #:for dtype in ['real32', 'real64', 'real128']
        subroutine fdata2pyplot_pass_${nd}$_${dtype}$_data( &
                       py_arr_name, fortran_arr, txt_name)
            character(*), intent(in) :: py_arr_name
            #:if nd == '1d'
            real(${dtype}$), intent(in) :: fortran_arr(:)
            #:endif
            #:if nd == '2d'
            real(${dtype}$), intent(in) :: fortran_arr(:,:)
            #:endif
            character(*), intent(in), optional :: txt_name

            integer :: unit
            #:if nd == '2d'
            integer :: i
            integer :: fortran_arr_shape(2)
            #:endif
            character(:), allocatable :: txt_name_
            character(:), allocatable :: py_cmd

            call init()

            if (present(txt_name)) then
                txt_name_ = txt_name
            else
                txt_name_ = py_arr_name
            end if

            unit = unopened_unit()
            open(unit=unit, file=txt_name_//'.txt', status='REPLACE', &
                 action='WRITE', position='APPEND')
            #:if nd == '1d'
            write(unit=unit, fmt=*) fortran_arr
            #:endif
            #:if nd == '2d'
            fortran_arr_shape = shape(fortran_arr)
            do i = 1, fortran_arr_shape(1)
                write(unit=unit, fmt=*) fortran_arr(i,:)
            end do
            #:endif
            close(unit=unit)

            unit = unopened_unit()
            open(unit=unit, file=py_file_name, status='OLD', &
                 action='WRITE', position='APPEND')
            py_cmd = py_arr_name//" = np.loadtxt('"//txt_name_//".txt')"
            write(unit=unit, fmt='(A)') py_cmd
            deallocate(py_cmd)
            close(unit=unit)

            deallocate(txt_name_)

        end subroutine fdata2pyplot_pass_${nd}$_${dtype}$_data

        #:endfor
        #:endfor
        subroutine fdata2pyplot_add_others(others)
            character(*), intent(in) :: others
            integer :: unit
            call init()
            unit = unopened_unit()
            open(unit=unit, file=py_file_name, status='OLD', &
                 action='WRITE', position='APPEND')
            write(unit=unit, fmt='(A)') others
            close(unit=unit)
        end subroutine fdata2pyplot_add_others
end module fdata2pyplot
